### ISSUE TITLE
Have function to print matrix associated with checksymp()

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/NonlinearNormalForm.jl#7]
This is helpful since looking at the significantly nonzero terms in this matrix gives clues as to where the non-symplecticity is happening.

**Comment by mattsignorelli** [comment]
Currently my checksymp returns 1-norm of transpose(M)*J*M - J. I'm thinking about instead making checksymp just return the matrix transpose(M)*J*M - J , and then the user  could calculate the norm if it is to be a quantified as just a single scalar number. How does that sound?

**Comment by DavidSagan** [comment]
Yes that sounds more modular. Do it.

**Comment by mattsignorelli** [comment]
added in latest commit [6a87b1f](https://github.com/bmad-sim/NonlinearNormalForm.jl/commit/6a87b1f53b5a6c83454707d94dfa89a4655d3e77)
