### ISSUE TITLE
TPSAMap negative powers bug

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/NonlinearNormalForm.jl#8]
For some reason, when writing (something)^(negative_number), Julia does not just call `^(something, negative_number)`. Instead it calls `inv(something)^(-1*negative_number)`. This definition does not agree with FPP. For example, for a TPSAMap `m`, `inv(m)^3 != inv(m^3)`. In fact `inv(m)^3` is very problematic, whereas `inv(m^3)` is not.

This is only a problem for TPSAMaps

**Comment by DavidSagan** [comment]
Solution is to define your own function `function Base.literal_pow(::typeof(^), a::A, b::Val{p}) where p` where `A` is the appropriate TPSA type.
